CREATE TABLE  vendedor (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
nombre VARCHAR( 100 ) NOT NULL ,
apellido VARCHAR( 100 ) NOT NULL ,
created_at TIMESTAMP NOT NULL ,
updated_at TIMESTAMP NOT NULL
) ENGINE = INNODB;

CREATE TABLE  producto (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
vendedor_id INT NOT NULL ,
descripcion VARCHAR( 255 ) NOT NULL ,
precio DECIMAL( 10, 2 ) NOT NULL ,
created_at TIMESTAMP NOT NULL ,
updated_at TIMESTAMP NOT NULL
) ENGINE = INNODB;
